### ISSUE TITLE
Temp basal not set due to predictions being NaN

### ISSUE THREAD

**Issue by MarkMpn** [MilosKozak/AndroidAPS#1041]
Using 2.0 RC3 with OpenAPS SMB.

Going low overnight, basal rate was not turned off. Logs show `minPredBG` as `NaN`. This seems to be triggered by `var fractionCarbsLeft = meal_data.mealCOB/meal_data.carbs;	` as `meal_data.carbs` is `0`

Inputs were:

```
Glucose status: {"glucose":60,"delta":-6,"short_avgdelta":-4.78,"long_avgdelta":-3.41,"date":1526178239000}
IOB data:       [{"iob":-0.004,"basaliob":-0.122,"bolussnooze":0,"activity":6.000000000000001E-4,"lastBolusTime":1526171962000,"time":"2018-05-13T02:25:00Z","iobWithZeroTemp":{"iob":-0.004,"basaliob":-0.122,"bolussnooze":0,"activity":6.000000000000001E-4,"lastBolusTime":1526171962000,"time":"2018-05-13T02:25:00Z"}},{"iob":-0.007,"basaliob":-0.115,"bolussnooze":0,"activity":5.0E-4,"lastBolusTime":1526171962000,"time":"2018-05-13T02:30:00Z","iobWithZeroTemp":{"iob":-0.018000000000000002,"basaliob":-0.126,"bolussnooze":0,"activity":5.0E-4,"lastBolusTime":1526171962000,"time":"2018-05-13T02:30:00Z"}},{"iob":-0.009000000000000001,"basaliob":-0.109,"bolussnooze":0,"activity":5.0E-4,"lastBolusTime":1526171962000,"time":"2018-05-13T02:35:00Z","iobWithZeroTemp":{"iob":-0.031,"basaliob":-0.131,"bolussnooze":0,"activity":5.0E-4,"lastBolusTime":1526171962000,"time":"2018-05-13T02:35:00Z"}},{"iob":-0.011,"basaliob":-0.10300000000000001,"bolussnooze":0,"activity":4.0E-4,"lastBolusTime":1526171962000,"time":"2018-05-13T02:40:00Z","iobWithZeroTemp":{"iob":-0.043000000000000003,"basaliob":-0.135,"bolussnooze":0,"activity":4.0E-4,"lastBolusTime":1526171962000,"time":"2018-05-13T02:40:00Z"}},{"iob":-0.013000000000000001,"basaliob":-0.097,"bolussnooze":0,"activity":3.0000000000000003E-4,"lastBolusTime":1526171962000,"time":"2018-05-13T02:45:00Z","iobWithZeroTemp":{"iob":-0.056,"basaliob":-0.14,"bolussnooze":0,"activity":2.0E-4,"lastBolusTime":1526171962000,"time":"2018-05-13T02:45:00Z"}},{"iob":-0.014,"basaliob":-0.091,"bolussnooze":0,"activity":3.0000000000000003E-4,"lastBolusTime":1526171962000,"time":"2018-05-13T02:50:00Z","iobWithZeroTemp":{"iob":-0.067,"basaliob":-0.14400000000000002,"bolussnooze":0,"activity":2.0E-4,"lastBolusTime":1526171962000,"time":"2018-05-13T02:50:00Z"}},{"iob":-0.016,"basaliob":-0.08600000000000001,"bolussnooze":0,"activity":2.0E-4,"lastBolusTime":1526171962000,"time":"2018-05-13T02:55:00Z","iobWithZeroTemp":{"iob":-0.079,"basaliob":-0.149,"bolussnooze":0,"activity":0,"lastBolusTime":1526171962000,"time":"2018-05-13T02:55:00Z"}},{"iob":-0.016,"basaliob":-0.08,"bolussnooze":0,"activity":2.0E-4,"lastBolusTime":1526171962000,"time":"2018-05-13T03:00:00Z","iobWithZeroTemp":{"iob":-0.089,"basaliob":-0.153,"bolussnooze":0,"activity":0,"lastBolusTime":1526171962000,"time":"2018-05-13T03:00:00Z"}},{"iob":-0.017,"basaliob":-0.075,"bolussnooze":0,"activity":1.0E-4,"lastBolusTime":1526171962000,"time":"2018-05-13T03:05:00Z","iobWithZeroTemp":{"iob":-0.099,"basaliob":-0.157,"bolussnooze":0,"activity":-2.0E-4,"lastBolusTime":1526171962000,"time":"2018-05-13T03:05:00Z"}},{"iob":-0.017,"basaliob":-0.07,"bolussnooze":0,"activity":1.0E-4,"lastBolusTime":1526171962000,"time":"2018-05-13T03:10:00Z","iobWithZeroTemp":{"iob":-0.108,"basaliob":-0.161,"bolussnooze":0,"activity":-2.0E-4,"lastBolusTime":1526171962000,"time":"2018-05-13T03:10:00Z"}},{"iob":-0.019,"basaliob":-0.066,"bolussnooze":0,"activity":1.0E-4,"lastBolusTime":1526171962000,"time":"2018-05-13T03:15:00Z","iobWithZeroTemp":{"iob":-0.11800000000000001,"basaliob":-0.165,"bolussnooze":0,"activity":-3.0000000000000003E-4,"lastBolusTime":1526171962000,"time":"2018-05-13T03:15:00Z"}},{"iob":-0.018000000000000002,"basaliob":-0.061,"bolussnooze":0,"activity":0,"lastBolusTime":1526171962000,"time":"2018-05-13T03:20:00Z","iobWithZeroTemp":{"iob":-0.125,"basaliob":-0.168,"bolussnooze":0,"activity":-4.0E-4,"lastBolusTime":1526171962000,"time":"2018-05-13T03:20:00Z"}},{"iob":-0.019,"basaliob":-0.057,"bolussnooze":0,"activity":0,"lastBolusTime":1526171962000,"time":"2018-05-13T03:25:00Z","iobWithZeroTemp":{"iob":-0.133,"basaliob":-0.171,"bolussnooze":0,"activity":-5.0E-4,"lastBolusTime":1526171962000,"time":"2018-05-13T03:25:00Z"}},{"iob":-0.019,"basaliob":-0.053,"bolussnooze":0,"activity":0,"lastBolusTime":1526171962000,"time":"2018-05-13T03:30:00Z","iobWithZeroTemp":{"iob":-0.14100000000000001,"basaliob":-0.17500000000000002,"bolussnooze":0,"activity":-6.000000000000001E-4,"lastBolusTime":1526171962000,"time":"2018-05-13T03:30:00Z"}},{"iob":-0.018000000000000002,"basaliob":-0.049,"bolussnooze":0,"activity":-1.0E-4,"lastBolusTime":1526171962000,"time":"2018-05-13T03:35:00Z","iobWithZeroTemp":{"iob":-0.147,"basaliob":-0.178,"bolussnooze":0,"activity":-7.0E-4,"lastBolusTime":1526171962000,"time":"2018-05-13T03:35:00Z"}},{"iob":-0.018000000000000002,"basaliob":-0.045,"bolussnooze":0,"activity":-1.0E-4,"lastBolusTime":1526171962000,"time":"2018-05-13T03:40:00Z","iobWithZeroTemp":{"iob":-0.154,"basaliob":-0.181,"bolussnooze":0,"activity":-8.0E-4,"lastBolusTime":1526171962000,"time":"2018-05-13T03:40:00Z"}},{"iob":-0.018000000000000002,"basaliob":-0.042,"bolussnooze":0,"activity":-1.0E-4,"lastBolusTime":1526171962000,"time":"2018-05-13T03:45:00Z","iobWithZeroTemp":{"iob":-0.16,"basaliob":-0.184,"bolussnooze":0,"activity":-8.0E-4,"lastBolusTime":1526171962000,"time":"2018-05-13T03:45:00Z"}},{"iob":-0.017,"basaliob":-0.038,"bolussnooze":0,"activity":-1.0E-4,"lastBolusTime":1526171962000,"time":"2018-05-13T03:50:00Z","iobWithZeroTemp":{"iob":-0.165,"basaliob":-0.186,"bolussnooze":0,"activity":-9.000000000000001E-4,"lastBolusTime":1526171962000,"time":"2018-05-13T03:50:00Z"}},{"iob":-0.016,"basaliob":-0.035,"bolussnooze":0,"activity":-1.0E-4,"lastBolusTime":1526171962000,"time":"2018-05-13T03:55:00Z","iobWithZeroTemp":{"iob":-0.17,"basaliob":-0.189,"bolussnooze":0,"activity":-0.001,"lastBolusTime":1526171962000,"time":"2018-05-13T03:55:00Z"}},{"iob":-0.016,"basaliob":-0.032,"bolussnooze":0,"activity":-1.0E-4,"lastBolusTime":1526171962000,"time":"2018-05-13T04:00:00Z","iobWithZeroTemp":{"iob":-0.17500000000000002,"basaliob":-0.191,"bolussnooze":0,"activity":-0.001,"lastBolusTime":1526171962000,"time":"2018-05-13T04:00:00Z"}},{"iob":-0.016,"basaliob":-0.03,"bolussnooze":0,"activity":-1.0E-4,"lastBolusTime":1526171962000,"time":"2018-05-13T04:05:00Z","iobWithZeroTemp":{"iob":-0.181,"basaliob":-0.195,"bolussnooze":0,"activity":-0.0011,"lastBolusTime":1526171962000,"time":"2018-05-13T04:05:00Z"}},{"iob":-0.015,"basaliob":-0.027,"bolussnooze":0,"activity":-1.0E-4,"lastBolusTime":1526171962000,"time":"2018-05-13T04:10:00Z","iobWithZeroTemp":{"iob":-0.186,"basaliob":-0.198,"bolussnooze":0,"activity":-0.0011,"lastBolusTime":1526171962000,"time":"2018-05-13T04:10:00Z"}},{"iob":-0.015,"basaliob":-0.025,"bolussnooze":0,"activity":-2.0E-4,"lastBolusTime":1526171962000,"time":"2018-05-13T04:15:00Z","iobWithZeroTemp":{"iob":-0.192,"basaliob":-0.202,"bolussnooze":0,"activity":-0.0013000000000000002,"lastBolusTime":1526171962000,"time":"2018-05-13T04:15:00Z"}},{"iob":-0.014,"basaliob":-0.022,"bolussnooze":0,"activity":-1.0E-4,"lastBolusTime":1526171962000,"time":"2018-05-13T04:20:00Z","iobWithZeroTemp":{"iob":-0.196,"basaliob":-0.20400000000000001,"bolussnooze":0,"activity":-0.0013000000000000002,"lastBolusTime":1526171962000,"time":"2018-05-13T04:20:00Z"}},{"iob":-0.013000000000000001,"basaliob":-0.02,"bolussnooze":0,"activity":-1.0E-4,"lastBolusTime":1526171962000,"time":"2018-05-13T04:25:00Z","iobWithZeroTemp":{"iob":-0.2,"basaliob":-0.20700000000000002,"bolussnooze":0,"activity":-0.0013000000000000002,"lastBolusTime":1526171962000,"time":"2018-05-13T04:25:00Z"}},{"iob":-0.012,"basaliob":-0.018000000000000002,"bolussnooze":0,"activity":-2.0E-4,"lastBolusTime":1526171962000,"time":"2018-05-13T04:30:00Z","iobWithZeroTemp":{"iob":-0.203,"basaliob":-0.209,"bolussnooze":0,"activity":-0.0015,"lastBolusTime":1526171962000,"time":"2018-05-13T04:30:00Z"}},{"iob":-0.011,"basaliob":-0.016,"bolussnooze":0,"activity":-1.0E-4,"lastBolusTime":1526171962000,"time":"2018-05-13T04:35:00Z","iobWithZeroTemp":{"iob":-0.20700000000000002,"basaliob":-0.212,"bolussnooze":0,"activity":-0.0014,"lastBolusTime":1526171962000,"time":"2018-05-13T04:35:00Z"}},{"iob":-0.011,"basaliob":-0.015,"bolussnooze":0,"activity":-1.0E-4,"lastBolusTime":1526171962000,"time":"2018-05-13T04:40:00Z","iobWithZeroTemp":{"iob":-0.211,"basaliob":-0.215,"bolussnooze":0,"activity":-0.0015,"lastBolusTime":1526171962000,"time":"2018-05-13T04:40:00Z"}},{"iob":-0.01,"basaliob":-0.013000000000000001,"bolussnooze":0,"activity":-2.0E-4,"lastBolusTime":1526171962000,"time":"2018-05-13T04:45:00Z","iobWithZeroTemp":{"iob":-0.214,"basaliob":-0.217,"bolussnooze":0,"activity":-0.0016,"lastBolusTime":1526171962000,"time":"2018-05-13T04:45:00Z"}},{"iob":-0.01,"basaliob":-0.012,"bolussnooze":0,"activity":-2.0E-4,"lastBolusTime":1526171962000,"time":"2018-05-13T04:50:00Z","iobWithZeroTemp":{"iob":-0.217,"basaliob":-0.219,"bolussnooze":0,"activity":-0.0017000000000000001,"lastBolusTime":1526171962000,"time":"2018-05-13T04:50:00Z"}},{"iob":-0.009000000000000001,"basaliob":-0.011,"bolussnooze":0,"activity":-2.0E-4,"lastBolusTime":1526171962000,"time":"2018-05-13T04:55:00Z","iobWithZeroTemp":{"iob":-0.219,"basaliob":-0.221,"bolussnooze":0,"activity":-0.0017000000000000001,"lastBolusTime":1526171962000,"time":"2018-05-13T04:55:00Z"}},{"iob":-0.008,"basaliob":-0.009000000000000001,"bolussnooze":0,"activity":-1.0E-4,"lastBolusTime":1526171962000,"time":"2018-05-13T05:00:00Z","iobWithZeroTemp":{"iob":-0.221,"basaliob":-0.222,"bolussnooze":0,"activity":-0.0017000000000000001,"lastBolusTime":1526171962000,"time":"2018-05-13T05:00:00Z"}},{"iob":-0.007,"basaliob":-0.008,"bolussnooze":0,"activity":-1.0E-4,"lastBolusTime":1526171962000,"time":"2018-05-13T05:05:00Z","iobWithZeroTemp":{"iob":-0.224,"basaliob":-0.225,"bolussnooze":0,"activity":-0.0017000000000000001,"lastBolusTime":1526171962000,"time":"2018-05-13T05:05:00Z"}},{"iob":-0.006,"basaliob":-0.007,"bolussnooze":0,"activity":-1.0E-4,"lastBolusTime":1526171962000,"time":"2018-05-13T05:10:00Z","iobWithZeroTemp":{"iob":-0.227,"basaliob":-0.228,"bolussnooze":0,"activity":-0.0018000000000000002,"lastBolusTime":1526171962000,"time":"2018-05-13T05:10:00Z"}},{"iob":-0.006,"basaliob":-0.006,"bolussnooze":0,"activity":-2.0E-4,"lastBolusTime":1526171962000,"time":"2018-05-13T05:15:00Z","iobWithZeroTemp":{"iob":-0.23,"basaliob":-0.23,"bolussnooze":0,"activity":-0.0019,"lastBolusTime":1526171962000,"time":"2018-05-13T05:15:00Z"}},{"iob":-0.005,"basaliob":-0.005,"bolussnooze":0,"activity":-2.0E-4,"lastBolusTime":1526171962000,"time":"2018-05-13T05:20:00Z","iobWithZeroTemp":{"iob":-0.232,"basaliob":-0.232,"bolussnooze":0,"activity":-0.0019,"lastBolusTime":1526171962000,"time":"2018-05-13T05:20:00Z"}},{"iob":-0.005,"basaliob":-0.005,"bolussnooze":0,"activity":-1.0E-4,"lastBolusTime":1526171962000,"time":"2018-05-13T05:25:00Z","iobWithZeroTemp":{"iob":-0.23500000000000001,"basaliob":-0.23500000000000001,"bolussnooze":0,"activity":-0.0019,"lastBolusTime":1526171962000,"time":"2018-05-13T05:25:00Z"}},{"iob":-0.004,"basaliob":-0.004,"bolussnooze":0,"activity":-1.0E-4,"lastBolusTime":1526171962000,"time":"2018-05-13T05:30:00Z","iobWithZeroTemp":{"iob":-0.23700000000000002,"basaliob":-0.23700000000000002,"bolussnooze":0,"activity":-0.0019,"lastBolusTime":1526171962000,"time":"2018-05-13T05:30:00Z"}},{"iob":-0.003,"basaliob":-0.003,"bolussnooze":0,"activity":-1.0E-4,"lastBolusTime":1526171962000,"time":"2018-05-13T05:35:00Z","iobWithZeroTemp":{"iob":-0.23800000000000002,"basaliob":-0.23800000000000002,"bolussnooze":0,"activity":-0.002,"lastBolusTime":1526171962000,"time":"2018-05-13T05:35:00Z"}},{"iob":-0.003,"basaliob":-0.003,"bolussnooze":0,"activity":-1.0E-4,"lastBolusTime":1526171962000,"time":"2018-05-13T05:40:00Z","iobWithZeroTemp":{"iob":-0.24,"basaliob":-0.24,"bolussnooze":0,"activity":-0.002,"lastBolusTime":1526171962000,"time":"2018-05-13T05:40:00Z"}},{"iob":-0.002,"basaliob":-0.002,"bolussnooze":0,"activity":-1.0E-4,"lastBolusTime":1526171962000,"time":"2018-05-13T05:45:00Z","iobWithZeroTemp":{"iob":-0.242,"basaliob":-0.242,"bolussnooze":0,"activity":-0.002,"lastBolusTime":1526171962000,"time":"2018-05-13T05:45:00Z"}},{"iob":-0.002,"basaliob":-0.002,"bolussnooze":0,"activity":-1.0E-4,"lastBolusTime":1526171962000,"time":"2018-05-13T05:50:00Z","iobWithZeroTemp":{"iob":-0.244,"basaliob":-0.244,"bolussnooze":0,"activity":-0.002,"lastBolusTime":1526171962000,"time":"2018-05-13T05:50:00Z"}},{"iob":-0.001,"basaliob":-0.001,"bolussnooze":0,"activity":-1.0E-4,"lastBolusTime":1526171962000,"time":"2018-05-13T05:55:00Z","iobWithZeroTemp":{"iob":-0.244,"basaliob":-0.244,"bolussnooze":0,"activity":-0.0021000000000000003,"lastBolusTime":1526171962000,"time":"2018-05-13T05:55:00Z"}},{"iob":-0.001,"basaliob":-0.001,"bolussnooze":0,"activity":-1.0E-4,"lastBolusTime":1526171962000,"time":"2018-05-13T06:00:00Z","iobWithZeroTemp":{"iob":-0.246,"basaliob":-0.246,"bolussnooze":0,"activity":-0.0021000000000000003,"lastBolusTime":1526171962000,"time":"2018-05-13T06:00:00Z"}},{"iob":-0.001,"basaliob":-0.001,"bolussnooze":0,"activity":0,"lastBolusTime":1526171962000,"time":"2018-05-13T06:05:00Z","iobWithZeroTemp":{"iob":-0.249,"basaliob":-0.249,"bolussnooze":0,"activity":-0.002,"lastBolusTime":1526171962000,"time":"2018-05-13T06:05:00Z"}},{"iob":-0.001,"basaliob":-0.001,"bolussnooze":0,"activity":0,"lastBolusTime":1526171962000,"time":"2018-05-13T06:10:00Z","iobWithZeroTemp":{"iob":-0.251,"basaliob":-0.251,"bolussnooze":0,"activity":-0.0021000000000000003,"lastBolusTime":1526171962000,"time":"2018-05-13T06:10:00Z"}},{"iob":0,"basaliob":0,"bolussnooze":0,"activity":0,"lastBolusTime":1526171962000,"time":"2018-05-13T06:15:00Z","iobWithZeroTemp":{"iob":-0.252,"basaliob":-0.252,"bolussnooze":0,"activity":-0.0021000000000000003,"lastBolusTime":1526171962000,"time":"2018-05-13T06:15:00Z"}},{"iob":0,"basaliob":0,"bolussnooze":0,"activity":0,"lastBolusTime":1526171962000,"time":"2018-05-13T06:20:00Z","iobWithZeroTemp":{"iob":-0.254,"basaliob":-0.254,"bolussnooze":0,"activity":-0.0021000000000000003,"lastBolusTime":1526171962000,"time":"2018-05-13T06:20:00Z"}}]
Current temp:   {"temp":"absolute","duration":0,"rate":0}
Profile:        {"max_iob":3,"type":"current","max_daily_basal":0.2,"max_basal":0.52,"min_bg":99,"max_bg":99,"target_bg":99,"carb_ratio":17,"sens":342,"max_daily_safety_multiplier":3,"current_basal_safety_multiplier":4,"high_temptarget_raises_sensitivity":false,"low_temptarget_lowers_sensitivity":false,"sensitivity_raises_target":true,"resistance_lowers_target":false,"adv_target_adjustments":false,"exercise_mode":false,"half_basal_exercise_target":160,"maxCOB":120,"skip_neutral_temps":true,"min_5m_carbimpact":3,"remainingCarbsCap":90,"enableUAM":true,"A52_risk_enable":false,"enableSMB_with_COB":true,"enableSMB_with_temptarget":true,"allowSMB_with_high_temptarget":false,"enableSMB_always":true,"enableSMB_after_carbs":true,"maxSMBBasalMinutes":60,"carbsReqThreshold":1,"current_basal":0.13,"temptargetSet":false,"autosens_max":1.2,"out_units":"mmol\/L"}
Meal data:      {"carbs":0,"boluses":0,"mealCOB":2.6047602339181197,"slopeFromMaxDeviation":0,"slopeFromMinDeviation":0.9999999999999999,"lastBolusTime":1526171962000,"lastCarbTime":0}
Autosens data:  {"ratio":1}
Reservoir data: undefined
MicroBolusAllowed:  true
SMBAlwaysAllowed:  true
```

Result of OpenAPS was:

```
{"temp":"absolute","bg":60,"tick":-6,"eventualBG":86,"insulinReq":0,"deliverAt":"2018-05-13T02:24:15.537Z","sensitivityRatio":1,"predBGs":{"IOB":[60,54,49,45,41,39,39,39,39,39,39,39,39],"ZT":[60,59,58,57,57,56,56,56,56,56,57,57,58,59,60,61,62,64,65,67,69,70,72,75,77,79,82,84,86,89,92,95,98],"COB":[60,55,50,46,42,40,39,39,39,39,39,39,39,42,44,46,49,52,55,58,61,63,66,68,70,72,74,76,77,79,80,81,82,83,83,84,84,84,85,85,85,85,85,85,86],"UAM":[60,54,49,45,41,39,39,39,39,39,39,39,39]},"COB":2.6047602339181197,"IOB":-0.004,"reason":"COB: 2.6047602339181197, Dev: -0.8, BGI: -0.1, ISF: 19.0, CR: 17, Target: 5.5, minPredBG NaN, minGuardBG NaN, IOBpredBG 2.2, COBpredBG 4.8, UAMpredBG 2.2; minGuardBG NaN<3.9","duration":null,"rate":0}
```

Error from `DetermineBasalResultSMB` was:

```
Error parsing determine-basal result JSON
org.json.JSONException: Value null at duration of type org.json.JSONObject$1 cannot be converted to int
	at org.json.JSON.typeMismatch(JSON.java:100) ~[na:0.0]
	at org.json.JSONObject.getInt(JSONObject.java:481) ~[na:0.0]
	at info.nightscout.androidaps.plugins.OpenAPSSMB.DetermineBasalResultSMB.<init>(DetermineBasalResultSMB.java:41) ~[na:0.0]
	at info.nightscout.androidaps.plugins.OpenAPSSMB.DetermineBasalAdapterSMBJS.invoke(DetermineBasalAdapterSMBJS.java:141) ~[na:0.0]
	at info.nightscout.androidaps.plugins.OpenAPSSMB.OpenAPSSMBPlugin.invoke(OpenAPSSMBPlugin.java:213) ~[na:0.0]
	at info.nightscout.androidaps.plugins.Loop.LoopPlugin.invoke(LoopPlugin.java:285) ~[na:0.0]
	at info.nightscout.androidaps.plugins.Loop.LoopPlugin.invoke(LoopPlugin.java:251) ~[na:0.0]
	at info.nightscout.androidaps.plugins.Loop.LoopPlugin.onStatusEvent(LoopPlugin.java:160) ~[na:0.0]
	at java.lang.reflect.Method.invoke(Native Method) ~[na:0.0]
	at com.squareup.otto.EventHandler.handleEvent(EventHandler.java:89) ~[na:0.0]
	at com.squareup.otto.Bus.dispatch(Bus.java:385) ~[na:0.0]
	at com.squareup.otto.Bus.dispatchQueuedEvents(Bus.java:368) ~[na:0.0]
	at com.squareup.otto.Bus.post(Bus.java:337) ~[na:0.0]
	at info.nightscout.androidaps.plugins.IobCobCalculator.IobCobThread.run(IobCobThread.java:272) ~[na:0.0]
```

Full log file is at https://github.com/MarkMpn/AndroidAPS/blob/minPredBGNaN/AndroidAPS%20minPredBG%20NaN.log

**Comment by MarkMpn** [comment]
It seems to work if `mealCOB` is also zero. It looks like `carbs` is taken from all carbs in `1.5 * dia`, and our `dia` is set to 5, so it should be looking back 7.5 hours. However, we have the max meal absorption time set to 8 hours, so we can have COB when `carbs` is zero.

I'm not sure where the fix should be here - is it our settings that are wrong, should AAPS be looking further back when calculating the value for `carbs`, or should OAPS handle having `mealCOB > 0` and `carbs = 0`, or some combination?

**Comment by AdrianLxM** [comment]
Actually both should read the same time when including/excluding treatments for `carbs` and for `cob`.

What I can think of is that COB is calculated before `carbs` so one treatment might have been included still in cob but not in carbs.

Did this continue to happen or was over 5 minutes later with the next value?

**Comment by MarkMpn** [comment]
This continued for some time. First happened at 02:29 and continued until 04:20. At 04:24 `mealCOB` became zero and the problem resolved.

**Comment by AdrianLxM** [comment]
How is the current status? Did you try it with a clean version?

**Comment by MarkMpn** [comment]
I changed the max meal absorption time to work around the problem, I’ll try to change it back again over the weekend at a time when the problem should occur during the day so we don’t risk another nighttime hypo and let you know. This was running the RC3 code, is there any other update/branch I should be testing it on?
