### ISSUE TITLE
[RC8] Open Loop Temp Basal not displayed on Overview after enacted

### ISSUE THREAD

**Issue by dansuk** [MilosKozak/AndroidAPS#1414]
Running RC8 in Open Loop mode, when a temporary basal is suggested and confirmed the new temp rate is not displayed on the Overview tab. The Loop tab shows that AAPS has recorded the temp basal being set but the Overview tab only reflects the original basal profile rate. After the next reading, the temp basal appears to be cancelled completely and is not shown on the Loop tab or Overview tab.

Please see some screenshots attached which were all taken at the same time after a temp basal suggestion of 50% l was confirmed and you will see the Overview tab does not display the temp basal.

![img_8479](https://user-images.githubusercontent.com/33720345/45375905-4dfbed80-b5ee-11e8-8894-668de817b97f.jpg)
![img_8480](https://user-images.githubusercontent.com/33720345/45375906-4dfbed80-b5ee-11e8-9d65-56654e5cb20d.jpg)
![img_8481](https://user-images.githubusercontent.com/33720345/45375907-4dfbed80-b5ee-11e8-86a2-bcaa9834773d.jpg)

**Comment by dansuk** [comment]
Log files here:
[AndroidAPS._2018-09-11_01-11-45_.2.zip](https://github.com/MilosKozak/AndroidAPS/files/2372079/AndroidAPS._2018-09-11_01-11-45_.2.zip)

**Comment by dansuk** [comment]
I do notice this in the log file:
13:16:23.575 [Thread-9102] E/DATABASE: [DatabaseHelper.createOrUpdate():891]: Unhandled exception
java.sql.SQLException: Unable to run insert stmt on object TemporaryBasal{date=1536668183000, date=9/11/18 13:16, isValid=true, pumpId=0, _id=null, percentRate=50, absoluteRate=0.0, durationInMinutes=30, isAbsolute=false, isFakeExtended=false, netExtendedRate=0.0}: INSERT INTO `TemporaryBasals` (`_id` ,`absoluteRate` ,`date` ,`durationInMinutes` ,`isAbsolute` ,`isValid` ,`percentRate` ,`pumpId` ,`source` ) VALUES (?,?,?,?,?,?,?,?,?)
	at com.j256.ormlite.misc.SqlExceptionUtil.create(SqlExceptionUtil.java:22) ~[na:0.0]
	at com.j256.ormlite.stmt.mapped.MappedCreate.insert(MappedCreate.java:135) ~[na:0.0]
	at com.j256.ormlite.stmt.StatementExecutor.create(StatementExecutor.java:406) ~[na:0.0]
	at com.j256.ormlite.dao.BaseDaoImpl.create(BaseDaoImpl.java:308) ~[na:0.0]
	at info.nightscout.androidaps.db.DatabaseHelper.createOrUpdate(DatabaseHelper.java:883) ~[na:0.0]
	at info.nightscout.androidaps.plugins.Treatments.TreatmentsPlugin.addToHistoryTempBasal(TreatmentsPlugin.java:483) ~[na:0.0]
	at info.nightscout.androidaps.plugins.PumpVirtual.VirtualPumpPlugin.setTempBasalPercent(VirtualPumpPlugin.java:308) ~[na:0.0]
	at info.nightscout.androidaps.queue.commands.CommandTempBasalPercent.execute(CommandTempBasalPercent.java:35) ~[na:0.0]
	at info.nightscout.androidaps.queue.QueueThread.run(QueueThread.java:145) ~[na:0.0]
Caused by: java.sql.SQLException: inserting to database failed: INSERT INTO `TemporaryBasals` (`_id` ,`absoluteRate` ,`date` ,`durationInMinutes` ,`isAbsolute` ,`isValid` ,`percentRate` ,`pumpId` ,`source` ) VALUES (?,?,?,?,?,?,?,?,?)
	at com.j256.ormlite.misc.SqlExceptionUtil.create(SqlExceptionUtil.java:22) ~[na:0.0]
	at com.j256.ormlite.android.AndroidDatabaseConnection.insert(AndroidDatabaseConnection.java:159) ~[na:0.0]
	at com.j256.ormlite.stmt.mapped.MappedCreate.insert(MappedCreate.java:91) ~[na:0.0]
	... 7 common frames omitted
Caused by: android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: TemporaryBasals.date (code 1555)
#################################################################
Error Code : 1555 (SQLITE_CONSTRAINT_PRIMARYKEY)
Caused By : Abort due to constraint violation.
	(UNIQUE constraint failed: TemporaryBasals.date (code 1555))
#################################################################
	at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method) ~[na:0.0]
	at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:926) ~[na:0.0]
	at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788) ~[na:0.0]
	at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86) ~[na:0.0]
	at com.j256.ormlite.android.AndroidDatabaseConnection.insert(AndroidDatabaseConnection.java:147) ~[na:0.0]
	... 8 common frames omitted
13:16:23.578 [Thread-9102] D/info.nightscout.androidaps.plugins.PumpVirtual.VirtualPumpPlugin: [VirtualPumpPlugin.setTempBasalPercent():310]: Settings temp basal percent: Success: true
Enacted: true
Comment: OK
Duration: 30 min
Percent: 50%

Not sure if that is the issue?

**Comment by MilosKozak** [comment]
do you upload your physical pump to NS?

**Comment by dansuk** [comment]
No my physical pump (Cellnovo) is not connected to Nightscout but CGM data is uploaded to Nightscout with xDrip+ as well as being read locally by AAPS.

**Comment by dansuk** [comment]
Possible database corruption? Would make sense that I remember it working ok at some stage and now it doesn't

**Comment by dansuk** [comment]
Also I used the Wear watchface and did accept a recommendation from that at one point.

**Comment by MilosKozak** [comment]
are you able to reproduce this bug?

**Comment by dansuk** [comment]
Thanks Milos. It occurred always with every temp suggestion for me.
