### ISSUE TITLE
[RC11, DanaRS] "Treatment could not be added to DB" for single older carbs and all new carb treatments

### ISSUE THREAD

**Issue by chaosbiber** [MilosKozak/AndroidAPS#1471]
After upgrading from RC10 to RC11 I've got an alarm telling me the _error_adding_treatment_message_ message for a random one or two treatments in the recent past (carbs, yesterday, see log file `carbs_from_day_before.log.txt`).

When trying to give normal carbs + bolus via bolus wizard the bolus went through and then the same alarm appeared. Also when adding (normal) carbs via carb-button, no matter if present or 10 to 20 minutes in the past. Log file: `adding_carbs.log.txt`
These carb treatments did not appear neither in treatments, nor in COB value and I believe (not 100% sure) that they also didn't arrived in nightscout. After downgrading back to rc10 and rebooting all those carb treatments appeared in the database (very high COB) and in nightscout.

**Steps to reproduce**
- using RC11 with a DanaRS
- entering carbs via Bolus wizard
- entering carbs the normal way, in my case without timeshift or with negative timeshift
- another facebook user says it happens when entering eCarbs
- another facebook user says it happens everytime with eCarbs and normal carbs
- another Gitter user says it happens with normal carbs **only without timeshift**

**Exception**
```
E/DATATREATMENTS: [TreatmentsPlugin.addToHistoryTreatment():541]: Treatment could not be added to DB
java.lang.Exception: null
	at info.nightscout.androidaps.plugins.Treatments.TreatmentsPlugin.addToHistoryTreatment(TreatmentsPlugin.java:541) ~[na:0.0]
	at info.nightscout.androidaps.plugins.PumpDanaRS.comm.DanaRS_Packet_APS_History_Events.handleMessage(DanaRS_Packet_APS_History_Events.java:200) ~[na:0.0]
	at info.nightscout.androidaps.plugins.PumpDanaRS.services.BLEComm.readDataParsing(BLEComm.java:542) ~[na:0.0]
	at info.nightscout.androidaps.plugins.PumpDanaRS.services.BLEComm.access$500(BLEComm.java:45) ~[na:0.0]
	at info.nightscout.androidaps.plugins.PumpDanaRS.services.BLEComm$1.lambda$onCharacteristicChanged$0$BLEComm$1(BLEComm.java:219) ~[na:0.0]
	at info.nightscout.androidaps.plugins.PumpDanaRS.services.BLEComm$1$$Lambda$0.run(Unknown Source) ~[na:0.0]
	at java.lang.Thread.run(Thread.java:761) ~[na:0.0]
```

I believe the error appears right after communicating with the Dana, but I'm not sure. When looking at my logs, search for `Treatment could not be added to DB`, starting at 04:37:50 for the historic data and 05:11:03 with the new bolus + carbs.

[carbs_from_day_before.log.txt](https://github.com/MilosKozak/AndroidAPS/files/2418096/carbs_from_day_before.log.txt)

[adding_carbs.log.txt](https://github.com/MilosKozak/AndroidAPS/files/2418094/adding_carbs.log.txt)

**Comment by chaosbiber** [comment]
I don't understand what exactly happens in that part of the code, but I can tell that in `TreatmentsPlugin.java` with RC10 `getService().createOrUpdate(treatment)` (510) gets called every time, but in RC11 this is splitted in bolus and carb treatments and `getService().createOrUpdate(carbsTreatment)` (530) won't get called for me as `detailedBolusInfo.carbTime` is always 0, doesn't matter if I add a timeshift or not. 
Thus `creatOrUpdateResult.or(creatOrUpdateResultCarbs);` (534) joins 2 empty/new results where `creatOrUpdateResult.success` is false and resulting in the Exception in line 541.

I don't know if `detailedBolusInfo.carbTime` is allowed to be zero and the reason for being zero is the bug, but when it is allowed to be zero, then perhaps `getService().createOrUpdate(carbsTreatment);` should move to a reachable position?
