### ISSUE TITLE
app crash repeatedly

### ISSUE THREAD

**Issue by andreascarsetto** [MilosKozak/AndroidAPS#1555]
Version 2.0
Phone Xiaomi Mi A2 Lite

I could not find the sequence of commands to reproduce the problem, it seems a random thing. Sometimes it happens that the app continues to crash repeatedly. 

The problem only occurs when I open the app(eg. to accept a basal). I generally use the smartwatch to confirm the basal change and I have no problem (i'm in open loop)

```
11-12 05:44:49.722  7884  7884 E AndroidRuntime: FATAL EXCEPTION: main
11-12 05:44:49.722  7884  7884 E AndroidRuntime: Process: info.nightscout.androidaps, PID: 7884
11-12 05:44:49.722  7884  7884 E AndroidRuntime: java.util.IllegalFormatFlagsException: Flags = ' ('
11-12 05:44:49.722  7884  7884 E AndroidRuntime: 	at java.util.Formatter$FormatSpecifier.checkText(Formatter.java:3131)
11-12 05:44:49.722  7884  7884 E AndroidRuntime: 	at java.util.Formatter$FormatSpecifier.<init>(Formatter.java:2824)
11-12 05:44:49.722  7884  7884 E AndroidRuntime: 	at java.util.Formatter$FormatSpecifierParser.<init>(Formatter.java:2624)
11-12 05:44:49.722  7884  7884 E AndroidRuntime: 	at java.util.Formatter.parse(Formatter.java:2557)
11-12 05:44:49.722  7884  7884 E AndroidRuntime: 	at java.util.Formatter.format(Formatter.java:2504)
11-12 05:44:49.722  7884  7884 E AndroidRuntime: 	at java.util.Formatter.format(Formatter.java:2458)
11-12 05:44:49.722  7884  7884 E AndroidRuntime: 	at java.lang.String.format(String.java:2814)
11-12 05:44:49.722  7884  7884 E AndroidRuntime: 	at android.content.res.Resources.getString(Resources.java:458)
11-12 05:44:49.722  7884  7884 E AndroidRuntime: 	at info.nightscout.androidaps.MainApp.gs(MainApp.java:273)
11-12 05:44:49.722  7884  7884 E AndroidRuntime: 	at info.nightscout.androidaps.plugins.PumpCombo.ComboFragment.lambda$updateGUI$32(ComboFragment.java:223)
11-12 05:44:49.722  7884  7884 E AndroidRuntime: 	at info.nightscout.androidaps.plugins.PumpCombo.-$$Lambda$ComboFragment$-fwwP8gAS4uqA182V57pi2Q57I4.run(Unknown Source:2)
```

[logcat.log](https://github.com/MilosKozak/AndroidAPS/files/2570623/logcat.log)
[AndroidAPS.log](https://github.com/MilosKozak/AndroidAPS/files/2570624/AndroidAPS.log)

**Comment by MilosKozak** [comment]
@jotomo could you check it please? it looks like combo part

**Comment by jotomo** [comment]
https://github.com/MilosKozak/AndroidAPS/pull/1557
