### ISSUE TITLE
[2.1] JSON Exception when parsing Combo data (from NS)

### ISSUE THREAD

**Issue by andyrozman** [MilosKozak/AndroidAPS#1659]
Build: 2.1

14:54:42.242 [IntentService[DataService]] D/DATASERVICE: [DataService.handleNewDataFromNSClient():138]: Got intent: info.nightscout.client.NEW_TREATMENT
14:54:42.261 [IntentService[DataService]] D/DATATREATMENTS: [TreatmentService.createOrUpdate():325]: Updating record by date from: NIGHTSCOUT Treatment{date= 1551240673000, date= 27 Feabh 2019 04:11:13, isValid= true, isSMB= false, _id= 1e4b96c4def84fcdb944e276, pumpId= 0, insulin= 0.0, carbs= 10.0, mealBolus= true}
14:54:42.264 [IntentService[DataService]] E/DATABASE: [DatabaseHelper.createTemptargetFromJsonIfNotExists():737]: Unhandled exception: {"_id":"0e1a4789b2b9465e90e68178","timestamp":1551240675000,"eventType":"Temporary Target","enteredBy":"AndroidAPS","uuid":"0e1a4789-b2b9-465e-90e6-8178ab336d30","created_at":"2019-02-27T04:11:15Z","sysTime":"2019-02-27T04:11:15.000+0000","mills":1551240675000,"mgdl":112}
org.json.JSONException: No value for duration
	at org.json.JSONObject.get(JSONObject.java:392) ~[na:0.0]
	at org.json.JSONObject.getInt(JSONObject.java:481) ~[na:0.0]
	at info.nightscout.androidaps.db.DatabaseHelper.createTemptargetFromJsonIfNotExists(DatabaseHelper.java:729) ~[na:0.0]
	at info.nightscout.androidaps.services.DataService.handleTreatmentFromNS(DataService.java:233) ~[na:0.0]
	at info.nightscout.androidaps.services.DataService.handleNewDataFromNSClient(DataService.java:152) ~[na:0.0]
	at info.nightscout.androidaps.services.DataService.onHandleIntent(DataService.java:109) ~[na:0.0]
	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:76) ~[na:0.0]
	at android.os.Handler.dispatchMessage(Handler.java:106) ~[na:0.0]
	at android.os.Looper.loop(Looper.java:164) ~[na:0.0]
	at android.os.HandlerThread.run(HandlerThread.java:65) ~[na:0.0]

I got some of this exceptions, and while I don't think they are very problemativ (it doesn't look like application crashes, but I have been having quite a few restarts after I upgraded).

**Comment by MilosKozak** [comment]
https://github.com/MilosKozak/AndroidAPS/commit/ec93045d84b0cd733dbef74d908d732bb67947ac
