### ISSUE TITLE
self initiated Profile update/switch (Insight) 

### ISSUE THREAD

**Issue by explodus** [MilosKozak/AndroidAPS#1713]
06:22:04.089 [EventThread] D/NSCLIENT: [NSClientPlugin.onStatusEvent():162]: PING received
06:22:09.149 [Disconnect Timer] I/PUMPCOMM: [InsightConnectionService.setState():267]: Insight state changed: DISCONNECTED

06:25:29.286 [main] D/CORE: [MainApp.onCreate():117]: onCreate
06:25:29.338 [main] I/DATABASE: [DatabaseHelper.onCreate():121]: onCreate
06:25:29.372 [main] I/CORE: [MainApp.onCreate():135]: Version: 2.2
06:25:29.372 [main] I/CORE: [MainApp.onCreate():136]: BuildVersion: NoGitSystemAvailable-2019.03.29-08:22

- seems that there is a restart of the App without any log entry 
- after initialization there are some exceptions
- then the profile is updated to the pump
- Smartphone is a Google Pixel XL and normally it doesn't close the App
- got that problem 2 times yesterday und today in the morning

06:25:33.670 [IntentService[DataService]] E/DATABASE: [DatabaseHelper.createProfileSwitchFromJsonIfNotExists():1653]: Unhandled exception: {"_id":"085f33704de4410cbcc3c071","timestamp":1550442666000,"eventType":"Profile Switch","enteredBy":"AndroidAPS","uuid":"085f3370-4de4-410c-bcc3-c0717ef6b509","created_at":"2019-02-17T22:31:06Z","sysTime":"2019-02-17T23:31:06.000+0100","mills":1550442666000,"mgdl":118}
org.json.JSONException: No value for profile
	at org.json.JSONObject.get(JSONObject.java:392) ~[na:0.0]
	at org.json.JSONObject.getString(JSONObject.java:553) ~[na:0.0]
	at info.nightscout.androidaps.db.DatabaseHelper.createProfileSwitchFromJsonIfNotExists(DatabaseHelper.java:1612) ~[na:0.0]
	at info.nightscout.androidaps.services.DataService.handleTreatmentFromNS(DataService.java:239) ~[na:0.0]
	at info.nightscout.androidaps.services.DataService.handleNewDataFromNSClient(DataService.java:152) ~[na:0.0]
	at info.nightscout.androidaps.services.DataService.onHandleIntent(DataService.java:109) ~[na:0.0]
	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:76) ~[na:0.0]
	at android.os.Handler.dispatchMessage(Handler.java:106) ~[na:0.0]
	at android.os.Looper.loop(Looper.java:193) ~[na:0.0]
	at android.os.HandlerThread.run(HandlerThread.java:65) ~[na:0.0]
06:25:33.672 [IntentService[DataService]] E/DATABASE: [DatabaseHelper.createProfileSwitchFromJsonIfNotExists():1653]: Unhandled exception: {"_id":"859fdc93744649839f843388","timestamp":1550443761000,"eventType":"Profile Switch","enteredBy":"AndroidAPS","uuid":"859fdc93-7446-4983-9f84-33881ff8f44a","created_at":"2019-02-17T22:49:21Z","sysTime":"2019-02-17T23:49:21.000+0100","mills":1550443761000,"mgdl":118}
org.json.JSONException: No value for profile
	at org.json.JSONObject.get(JSONObject.java:392) ~[na:0.0]
	at org.json.JSONObject.getString(JSONObject.java:553) ~[na:0.0]
	at info.nightscout.androidaps.db.DatabaseHelper.createProfileSwitchFromJsonIfNotExists(DatabaseHelper.java:1612) ~[na:0.0]
	at info.nightscout.androidaps.services.DataService.handleTreatmentFromNS(DataService.java:239) ~[na:0.0]
	at info.nightscout.androidaps.services.DataService.handleNewDataFromNSClient(DataService.java:152) ~[na:0.0]
	at info.nightscout.androidaps.services.DataService.onHandleIntent(DataService.java:109) ~[na:0.0]
	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:76) ~[na:0.0]
	at android.os.Handler.dispatchMessage(Handler.java:106) ~[na:0.0]
	at android.os.Looper.loop(Looper.java:193) ~[na:0.0]
	at android.os.HandlerThread.run(HandlerThread.java:65) ~[na:0.0]
06:25:33.674 [IntentService[DataService]] E/DATABASE: [DatabaseHelper.createProfileSwitchFromJsonIfNotExists():1653]: Unhandled exception: {"_id":"e18bc91a341d474e982012a2","timestamp":1550443775000,"eventType":"Profile Switch","enteredBy":"AndroidAPS","uuid":"e18bc91a-341d-474e-9820-12a207d61a0a","created_at":"2019-02-17T22:49:35Z","sysTime":"2019-02-17T23:49:35.000+0100","mills":1550443775000,"mgdl":118}
org.json.JSONException: No value for profile
	at org.json.JSONObject.get(JSONObject.java:392) ~[na:0.0]
	at org.json.JSONObject.getString(JSONObject.java:553) ~[na:0.0]
	at info.nightscout.androidaps.db.DatabaseHelper.createProfileSwitchFromJsonIfNotExists(DatabaseHelper.java:1612) ~[na:0.0]
	at info.nightscout.androidaps.services.DataService.handleTreatmentFromNS(DataService.java:239) ~[na:0.0]
	at info.nightscout.androidaps.services.DataService.handleNewDataFromNSClient(DataService.java:152) ~[na:0.0]
	at info.nightscout.androidaps.services.DataService.onHandleIntent(DataService.java:109) ~[na:0.0]
	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:76) ~[na:0.0]
	at android.os.Handler.dispatchMessage(Handler.java:106) ~[na:0.0]
	at android.os.Looper.loop(Looper.java:193) ~[na:0.0]
	at android.os.HandlerThread.run(HandlerThread.java:65) ~[na:0.0]
06:25:33.675 [IntentService[DataService]] E/DATABASE: [DatabaseHelper.createProfileSwitchFromJsonIfNotExists():1653]: Unhandled exception: {"_id":"f727b0850e4340c1838dfbd4","timestamp":1550474596000,"eventType":"Profile Switch","enteredBy":"AndroidAPS","uuid":"f727b085-0e43-40c1-838d-fbd492c5afa3","created_at":"2019-02-18T07:23:16Z","sysTime":"2019-02-18T08:23:16.000+0100","mills":1550474596000,"mgdl":118}
org.json.JSONException: No value for profile
	at org.json.JSONObject.get(JSONObject.java:392) ~[na:0.0]
	at org.json.JSONObject.getString(JSONObject.java:553) ~[na:0.0]
	at info.nightscout.androidaps.db.DatabaseHelper.createProfileSwitchFromJsonIfNotExists(DatabaseHelper.java:1612) ~[na:0.0]
	at info.nightscout.androidaps.services.DataService.handleTreatmentFromNS(DataService.java:239) ~[na:0.0]
	at info.nightscout.androidaps.services.DataService.handleNewDataFromNSClient(DataService.java:152) ~[na:0.0]
	at info.nightscout.androidaps.services.DataService.onHandleIntent(DataService.java:109) ~[na:0.0]
	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:76) ~[na:0.0]
	at android.os.Handler.dispatchMessage(Handler.java:106) ~[na:0.0]
	at android.os.Looper.loop(Looper.java:193) ~[na:0.0]
	at android.os.HandlerThread.run(HandlerThread.java:65) ~[na:0.0]
06:25:33.676 [IntentService[DataService]] E/DATABASE: [DatabaseHelper.createProfileSwitchFromJsonIfNotExists():1653]: Unhandled exception: {"_id":"7bb1074eb2b4408ea1218a41","timestamp":1550474609000,"eventType":"Profile Switch","enteredBy":"AndroidAPS","uuid":"7bb1074e-b2b4-408e-a121-8a414b9cbb35","created_at":"2019-02-18T07:23:29Z","sysTime":"2019-02-18T08:23:29.000+0100","mills":1550474609000,"mgdl":118}
org.json.JSONException: No value for profile
	at org.json.JSONObject.get(JSONObject.java:392) ~[na:0.0]
	at org.json.JSONObject.getString(JSONObject.java:553) ~[na:0.0]
	at info.nightscout.androidaps.db.DatabaseHelper.createProfileSwitchFromJsonIfNotExists(DatabaseHelper.java:1612) ~[na:0.0]
	at info.nightscout.androidaps.services.DataService.handleTreatmentFromNS(DataService.java:239) ~[na:0.0]
	at info.nightscout.androidaps.services.DataService.handleNewDataFromNSClient(DataService.java:152) ~[na:0.0]
	at info.nightscout.androidaps.services.DataService.onHandleIntent(DataService.java:109) ~[na:0.0]
	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:76) ~[na:0.0]
	at android.os.Handler.dispatchMessage(Handler.java:106) ~[na:0.0]
	at android.os.Looper.loop(Looper.java:193) ~[na:0.0]
	at android.os.HandlerThread.run(HandlerThread.java:65) ~[na:0.0]
06:25:33.680 [IntentService[DataService]] D/DATABASE: [DatabaseHelper.createOrUpdate():1517]: PROFILESWITCH: Updating record by date from: USER ProfileSwitch{date=1550491967000date=18.02.19 13:12, isValid=true, duration=0, profileName=LocalProfile, percentage=100, timeshift=0}
06:25:33.681 [IntentService[DataService]] E/DATABASE: [DatabaseHelper.createProfileSwitchFromJsonIfNotExists():1653]: Unhandled exception: {"_id":"4660b298747c441f9be24377","timestamp":1550491967000,"eventType":"Profile Switch","enteredBy":"AndroidAPS","uuid":"4660b298-747c-441f-9be2-4377b47f7e92","created_at":"2019-02-18T12:12:47Z","sysTime":"2019-02-18T13:12:47.000+0100","mills":1550491967000,"mgdl":118}
org.json.JSONException: No value for profile
	at org.json.JSONObject.get(JSONObject.java:392) ~[na:0.0]
	at org.json.JSONObject.getString(JSONObject.java:553) ~[na:0.0]
	at info.nightscout.androidaps.db.DatabaseHelper.createProfileSwitchFromJsonIfNotExists(DatabaseHelper.java:1612) ~[na:0.0]
	at info.nightscout.androidaps.services.DataService.handleTreatmentFromNS(DataService.java:239) ~[na:0.0]
	at info.nightscout.androidaps.services.DataService.handleNewDataFromNSClient(DataService.java:152) ~[na:0.0]
	at info.nightscout.androidaps.services.DataService.onHandleIntent(DataService.java:109) ~[na:0.0]
	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:76) ~[na:0.0]
	at android.os.Handler.dispatchMessage(Handler.java:106) ~[na:0.0]
	at android.os.Looper.loop(Looper.java:193) ~[na:0.0]
	at android.os.HandlerThread.run(HandlerThread.java:65) ~[na:0.0]
06:25:33.874 [IntentService[DataService]] D/DATABASE: [DatabaseHelper.createOrUpdate():1517]: PROFILESWITCH: Updating record by date from: USER ProfileSwitch{date=1550562418000date=19.02.19 08:46, isValid=true, duration=0, profileName=LocalProfile, percentage=100, timeshift=0}
06:25:33.875 [IntentService[DataService]] E/DATABASE: [DatabaseHelper.createProfileSwitchFromJsonIfNotExists():1653]: Unhandled exception: {"_id":"960f22825b284bee8a99e338","timestamp":1550562418000,"eventType":"Profile Switch","enteredBy":"AndroidAPS","uuid":"960f2282-5b28-4bee-8a99-e338a89f6d5d","created_at":"2019-02-19T07:46:58Z","sysTime":"2019-02-19T08:46:58.000+0100","mills":1550562418000,"mgdl":118}
org.json.JSONException: No value for profile
	at org.json.JSONObject.get(JSONObject.java:392) ~[na:0.0]
	at org.json.JSONObject.getString(JSONObject.java:553) ~[na:0.0]
	at info.nightscout.androidaps.db.DatabaseHelper.createProfileSwitchFromJsonIfNotExists(DatabaseHelper.java:1612) ~[na:0.0]
	at info.nightscout.androidaps.services.DataService.handleTreatmentFromNS(DataService.java:239) ~[na:0.0]
	at info.nightscout.androidaps.services.DataService.handleNewDataFromNSClient(DataService.java:152) ~[na:0.0]
	at info.nightscout.androidaps.services.DataService.onHandleIntent(DataService.java:109) ~[na:0.0]
	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:76) ~[na:0.0]
	at android.os.Handler.dispatchMessage(Handler.java:106) ~[na:0.0]
	at android.os.Looper.loop(Looper.java:193) ~[na:0.0]
	at android.os.HandlerThread.run(HandlerThread.java:65) ~[na:0.0]
06:25:33.877 [IntentService[DataService]] D/DATABASE: [DatabaseHelper.createOrUpdate():1517]: PROFILESWITCH: Updating record by date from: USER ProfileSwitch{date=1550562433000date=19.02.19 08:47, isValid=true, duration=0, profileName=LocalProfile, percentage=100, timeshift=0}
06:25:33.879 [IntentService[DataService]] E/DATABASE: [DatabaseHelper.createProfileSwitchFromJsonIfNotExists():1653]: Unhandled exception: {"_id":"34f4d7faa4714d3d853ce81f","timestamp":1550562433000,"eventType":"Profile Switch","enteredBy":"AndroidAPS","uuid":"34f4d7fa-a471-4d3d-853c-e81f5d38cdea","created_at":"2019-02-19T07:47:13Z","sysTime":"2019-02-19T08:47:13.000+0100","mills":1550562433000,"mgdl":118}
org.json.JSONException: No value for profile
	at org.json.JSONObject.get(JSONObject.java:392) ~[na:0.0]
	at org.json.JSONObject.getString(JSONObject.java:553) ~[na:0.0]
	at info.nightscout.androidaps.db.DatabaseHelper.createProfileSwitchFromJsonIfNotExists(DatabaseHelper.java:1612) ~[na:0.0]
	at info.nightscout.androidaps.services.DataService.handleTreatmentFromNS(DataService.java:239) ~[na:0.0]
	at info.nightscout.androidaps.services.DataService.handleNewDataFromNSClient(DataService.java:152) ~[na:0.0]
	at info.nightscout.androidaps.services.DataService.onHandleIntent(DataService.java:109) ~[na:0.0]
	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:76) ~[na:0.0]
	at android.os.Handler.dispatchMessage(Handler.java:106) ~[na:0.0]
	at android.os.Looper.loop(Looper.java:193) ~[na:0.0]
	at android.os.HandlerThread.run(HandlerThread.java:65) ~[na:0.0]
06:25:33.881 [IntentService[DataService]] D/DATABASE: [DatabaseHelper.createOrUpdate():1517]: PROFILESWITCH: Updating record by date from: USER ProfileSwitch{date=1550562880000date=19.02.19 08:54, isValid=true, duration=0, profileName=LocalProfile, percentage=100, timeshift=0}
06:25:33.883 [IntentService[DataService]] E/DATABASE: [DatabaseHelper.createProfileSwitchFromJsonIfNotExists():1653]: Unhandled exception: {"_id":"4e316800737247248bab4f32","timestamp":1550562880000,"eventType":"Profile Switch","enteredBy":"AndroidAPS","uuid":"4e316800-7372-4724-8bab-4f32f9b231c5","created_at":"2019-02-19T07:54:40Z","sysTime":"2019-02-19T08:54:40.000+0100","mills":1550562880000,"mgdl":118}
org.json.JSONException: No value for profile
	at org.json.JSONObject.get(JSONObject.java:392) ~[na:0.0]
	at org.json.JSONObject.getString(JSONObject.java:553) ~[na:0.0]
	at info.nightscout.androidaps.db.DatabaseHelper.createProfileSwitchFromJsonIfNotExists(DatabaseHelper.java:1612) ~[na:0.0]
	at info.nightscout.androidaps.services.DataService.handleTreatmentFromNS(DataService.java:239) ~[na:0.0]
	at info.nightscout.androidaps.services.DataService.handleNewDataFromNSClient(DataService.java:152) ~[na:0.0]
	at info.nightscout.androidaps.services.DataService.onHandleIntent(DataService.java:109) ~[na:0.0]
	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:76) ~[na:0.0]
	at android.os.Handler.dispatchMessage(Handler.java:106) ~[na:0.0]
	at android.os.Looper.loop(Looper.java:193) ~[na:0.0]
	at android.os.HandlerThread.run(HandlerThread.java:65) ~[na:0.0]
06:25:33.884 [IntentService[DataService]] E/DATABASE: [DatabaseHelper.createProfileSwitchFromJsonIfNotExists():1653]: Unhandled exception: {"_id":"1f2b41ade0334830b3a63e4e","timestamp":1550599588000,"eventType":"Profile Switch","enteredBy":"AndroidAPS","uuid":"1f2b41ad-e033-4830-b3a6-3e4e44eefbfd","created_at":"2019-02-19T18:06:28Z","sysTime":"2019-02-19T19:06:28.000+0100","mills":1550599588000,"mgdl":118}
org.json.JSONException: No value for profile
	at org.json.JSONObject.get(JSONObject.java:392) ~[na:0.0]
	at org.json.JSONObject.getString(JSONObject.java:553) ~[na:0.0]
	at info.nightscout.androidaps.db.DatabaseHelper.createProfileSwitchFromJsonIfNotExists(DatabaseHelper.java:1612) ~[na:0.0]
	at info.nightscout.androidaps.services.DataService.handleTreatmentFromNS(DataService.java:239) ~[na:0.0]
	at info.nightscout.androidaps.services.DataService.handleNewDataFromNSClient(DataService.java:152) ~[na:0.0]
	at info.nightscout.androidaps.services.DataService.onHandleIntent(DataService.java:109) ~[na:0.0]
	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:76) ~[na:0.0]
	at android.os.Handler.dispatchMessage(Handler.java:106) ~[na:0.0]
	at android.os.Looper.loop(Looper.java:193) ~[na:0.0]
	at android.os.HandlerThread.run(HandlerThread.java:65) ~[na:0.0]
06:25:33.890 [IntentService[DataService]] D/DATABASE: [DatabaseHelper.createOrUpdate():1517]: PROFILESWITCH: Updating record by date from: USER ProfileSwitch{date=1550599588000date=19.02.19 19:06, isValid=true, duration=0, profileName=LocalProfile, percentage=100, timeshift=0}
06:25:33.891 [IntentService[DataService]] D/DATABASE: [DatabaseHelper.createOrUpdate():1517]: PROFILESWITCH: Updating record by date from: USER ProfileSwitch{date=1550599611000date=19.02.19 19:06, isValid=true, duration=0, profileName=LocalProfile, percentage=100, timeshift=0}
06:25:33.893 [IntentService[DataService]] E/DATABASE: [DatabaseHelper.createProfileSwitchFromJsonIfNotExists():1653]: Unhandled exception: {"_id":"5a2606e05cff4c8995d5d63c","timestamp":1550599611000,"eventType":"Profile Switch","enteredBy":"AndroidAPS","uuid":"5a2606e0-5cff-4c89-95d5-d63ce889eb0f","created_at":"2019-02-19T18:06:51Z","sysTime":"2019-02-19T19:06:51.000+0100","mills":1550599611000,"mgdl":118}
org.json.JSONException: No value for profile
	at org.json.JSONObject.get(JSONObject.java:392) ~[na:0.0]
	at org.json.JSONObject.getString(JSONObject.java:553) ~[na:0.0]
	at info.nightscout.androidaps.db.DatabaseHelper.createProfileSwitchFromJsonIfNotExists(DatabaseHelper.java:1612) ~[na:0.0]
	at info.nightscout.androidaps.services.DataService.handleTreatmentFromNS(DataService.java:239) ~[na:0.0]
	at info.nightscout.androidaps.services.DataService.handleNewDataFromNSClient(DataService.java:152) ~[na:0.0]
	at info.nightscout.androidaps.services.DataService.onHandleIntent(DataService.java:109) ~[na:0.0]
	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:76) ~[na:0.0]
	at android.os.Handler.dispatchMessage(Handler.java:106) ~[na:0.0]
	at android.os.Looper.loop(Looper.java:193) ~[na:0.0]
	at android.os.HandlerThread.run(HandlerThread.java:65) ~[na:0.0]
06:25:33.895 [IntentService[DataService]] D/DATABASE: [DatabaseHelper.createOrUpdate():1517]: PROFILESWITCH: Updating record by date from: USER ProfileSwitch{date=1550600595000date=19.02.19 19:23, isValid=true, duration=0, profileName=LocalProfile, percentage=100, timeshift=0}
06:25:33.896 [IntentService[DataService]] E/DATABASE: [DatabaseHelper.createProfileSwitchFromJsonIfNotExists():1653]: Unhandled exception: {"_id":"7c2d784a76454297b1f96990","timestamp":1550600595000,"eventType":"Profile Switch","enteredBy":"AndroidAPS","uuid":"7c2d784a-7645-4297-b1f9-69900feaae27","created_at":"2019-02-19T18:23:15Z","sysTime":"2019-02-19T19:23:15.000+0100","mills":1550600595000,"mgdl":118}
org.json.JSONException: No value for profile
	at org.json.JSONObject.get(JSONObject.java:392) ~[na:0.0]
	at org.json.JSONObject.getString(JSONObject.java:553) ~[na:0.0]
	at info.nightscout.androidaps.db.DatabaseHelper.createProfileSwitchFromJsonIfNotExists(DatabaseHelper.java:1612) ~[na:0.0]
	at info.nightscout.androidaps.services.DataService.handleTreatmentFromNS(DataService.java:239) ~[na:0.0]
	at info.nightscout.androidaps.services.DataService.handleNewDataFromNSClient(DataService.java:152) ~[na:0.0]
	at info.nightscout.androidaps.services.DataService.onHandleIntent(DataService.java:109) ~[na:0.0]
	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:76) ~[na:0.0]
	at android.os.Handler.dispatchMessage(Handler.java:106) ~[na:0.0]
	at android.os.Looper.loop(Looper.java:193) ~[na:0.0]
	at android.os.HandlerThread.run(HandlerThread.java:65) ~[na:0.0]

06:25:33.898 [IntentService[DataService]] D/DATABASE: [DatabaseHelper.createOrUpdate():1517]: PROFILESWITCH: Updating record by date from: USER ProfileSwitch{date=1550600674000date=19.02.19 19:24, isValid=true, duration=0, profileName=LocalProfile, percentage=100, timeshift=0}

[AndroidAPS._2019-04-05_06-22-09_.txt](https://github.com/MilosKozak/AndroidAPS/files/3046843/AndroidAPS._2019-04-05_06-22-09_.txt)

**Comment by TebbeUbben** [comment]
Nightscout...

**Comment by explodus** [comment]
> Nightscout...

the error with the invalid profile comes also with a local profil, without NS profil.

**Comment by TebbeUbben** [comment]
Can you reproduce the rror?

**Comment by explodus** [comment]
Sure, with any profile switch.

**Comment by TebbeUbben** [comment]
May you send me the basal values in your profile?

**Comment by TebbeUbben** [comment]
Closing due to getting no response from the reporter.
