### ISSUE TITLE
App crash when module SMS communicator activated

### ISSUE THREAD

**Issue by maskac** [MilosKozak/AndroidAPS#1789]
When is config clean (no existing previos configuration) , after activating SMS communicator, when i want access Preferences or configuration of SMS comunicator app crash.

Tested on AndroidAPS 2.3
Andorid version 9 and 7.1

**Comment by jotomo** [comment]
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: info.nightscout.androidaps, PID: 4565
    java.lang.RuntimeException: Unable to start activity ComponentInfo{info.nightscout.androidaps/info.nightscout.androidaps.activities.PreferencesActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.trim()' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2913)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.trim()' on a null object reference
        at info.nightscout.androidaps.activities.PreferencesActivity.updatePrefSummary(PreferencesActivity.java:96)
        at info.nightscout.androidaps.activities.PreferencesActivity.initSummary(PreferencesActivity.java:109)
        at info.nightscout.androidaps.activities.PreferencesActivity.initSummary(PreferencesActivity.java:106)
        at info.nightscout.androidaps.activities.PreferencesActivity.initSummary(PreferencesActivity.java:106)
        at info.nightscout.androidaps.activities.PreferencesActivity$MyPreferenceFragment.onCreate(PreferencesActivity.java:205)
        at android.app.Fragment.performCreate(Fragment.java:2503)
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1256)
        at android.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1319)
        at android.app.FragmentTransition.calculateFragments(FragmentTransition.java:1203)
        at android.app.FragmentTransition.startTransitions(FragmentTransition.java:101)
        at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2197)
        at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2155)
        at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2062)
        at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3051)
        at android.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:2998)
        at android.app.FragmentController.dispatchActivityCreated(FragmentController.java:182)
        at android.app.Activity.performCreate(Activity.java:7143)
        at android.app.Activity.performCreate(Activity.java:7127)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
```

**Comment by MilosKozak** [comment]
it's already resolved here. but not merged yet
https://github.com/MilosKozak/AndroidAPS/pull/1781
