### ISSUE TITLE
2.6.6-dev Crash on History Browser selection

### ISSUE THREAD

**Issue by Philoul** [MilosKozak/AndroidAPS#2697]
I just updated my local dev with latest commits and now AAPS crash when I select History Browser...
```
    Process: info.nightscout.androidaps, PID: 11157
    java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.get(ArrayList.java:437)
        at info.nightscout.androidaps.historyBrowser.HistoryBrowseActivity$updateGUI$1.invokeSuspend(HistoryBrowseActivity.kt:352)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:7860)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
2020-06-02 01:09:57.703 ? E/InputDispatcher: channel '19d218b info.nightscout.androidaps/info.nightscout.androidaps.historyBrowser.HistoryBrowseActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
2020-06-02 01:09:57.728 ? E/WindowManager: RemoteException occurs on reporting focusChanged, w=Window{19d218b u0 info.nightscout.androidaps/info.nightscout.androidaps.historyBrowser.HistoryBrowseActivity EXITING}
    android.os.DeadObjectException
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(BinderProxy.java:527)
        at android.view.IWindow$Stub$Proxy.windowFocusChanged(IWindow.java:813)
        at com.android.server.wm.WindowState.reportFocusChangedSerialized(WindowState.java:3633)
        at com.android.server.wm.WindowManagerService$H.handleMessage(WindowManagerService.java:5189)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.os.HandlerThread.run(HandlerThread.java:67)
        at com.android.server.ServiceThread.run(ServiceThread.java:44)
2020-06-02 01:09:57.737 ? E/WindowManager: win=Window{19d218b u0 info.nightscout.androidaps/info.nightscout.androidaps.historyBrowser.HistoryBrowseActivity EXITING} destroySurfaces: appStopped=false win.mWindowRemovalAllowed=true win.mRemoveOnExit=true win.mViewVisibility=0 caller=com.android.server.wm.AppWindowToken.destroySurfaces:1199 com.android.server.wm.AppWindowToken.destroySurfaces:1180 com.android.server.wm.WindowState.onExitAnimationDone:5030 com.android.server.wm.-$$Lambda$01bPtngJg5AqEoOWfW3rWfV7MH4.accept:2 java.util.ArrayList.forEach:1262 com.android.server.wm.AppWindowToken.onAnimationFinished:3535 com.android.server.wm.AppWindowToken.commitVisibility:859 
```

**Comment by Philoul** [comment]
The origin of this crash seems to be this commit : https://github.com/MilosKozak/AndroidAPS/commit/31b31775610cd6080ce2a9f64bddcddd44c61595

(If I revert only this commit I don't have crash...)

**Comment by MilosKozak** [comment]
https://github.com/MilosKozak/AndroidAPS/commit/064389d066f66bc17665cab485f3975db012f8e8
