### ISSUE TITLE
[2.7.0-RC1] Json problem with MDT History retrieval

### ISSUE THREAD

**Issue by andyrozman** [MilosKozak/AndroidAPS#2839]
Problem happens when json of data is created, while retrieving Medtronic Pump History. 

 SensitivityAAPSPlugin has its own instance of SP (sp), while AbstractSensitivityPlugin also has one.

Proposed solution: change variable sp (lateinit var) so that it is visible in all children.

Log excerpt:

17:08:34.395 [Thread-10] D/PUMP: [MedtronicHistoryData.getOldestTimestamp():1365]: DoubleBolusDebug: getOldestTimestamp. Oldest entry found: time=[20200720081949, PumpHistoryEntry [DT: 20.07.2020 08:19:49, Object=BolusDTO [type=Normal, 1.10]]], object={}
17:08:34.395 [Thread-10] D/PUMP: [MedtronicHistoryData.getOldestTimestamp():1371]: DoubleBolusDebug: getOldestTimestamp. oldestEntryTime: [20.07.2020 08:19:49]
17:08:34.395 [Thread-10] D/PUMP: [MedtronicHistoryData.getOldestTimestamp():1375]: DoubleBolusDebug: getOldestTimestamp. oldestEntryTime (-2m): [20.07.2020 08:17:49, 1595247469000], timeInMillis={}
17:08:34.419 [Thread-10] E/CORE: [MedtronicHistoryData.processNewHistoryData():464]: ProcessHistoryData: Error processing Bolus entries: class info.nightscout.androidaps.plugins.sensitivity.SensitivityAAPSPlugin declares multiple JSON fields named sp
java.lang.IllegalArgumentException: class info.nightscout.androidaps.plugins.sensitivity.SensitivityAAPSPlugin declares multiple JSON fields named sp
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:172) ~[na:0.0]
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102) ~[na:0.0]
    at com.google.gson.Gson.getAdapter(Gson.java:458) ~[na:0.0]
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:117) ~[na:0.0]
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:166) ~[na:0.0]
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102) ~[na:0.0]
    at com.google.gson.Gson.getAdapter(Gson.java:458) ~[na:0.0]
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:117) ~[na:0.0]
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:166) ~[na:0.0]
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102) ~[na:0.0]
    at com.google.gson.Gson.getAdapter(Gson.java:458) ~[na:0.0]
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:117) ~[na:0.0]
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:166) ~[na:0.0]
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102) ~[na:0.0]
    at com.google.gson.Gson.getAdapter(Gson.java:458) ~[na:0.0]
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.createBoundField(ReflectiveTypeAdapterFactory.java:117) ~[na:0.0]
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:166) ~[na:0.0]
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:102) ~[na:0.0]
    at com.google.gson.Gson.getAdapter(Gson.java:458) ~[na:0.0]
    at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:56) ~[na:0.0]
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:127) ~[na:0.0]
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:245) ~[na:0.0]
    at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69) ~[na:0.0]
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:127) ~[na:0.0]
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:245) ~[na:0.0]
    at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69) ~[na:0.0]
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:127) ~[na:0.0]
    at com.google.gson.internal.bind.ReflectiveTypeAdapte

**Comment by MilosKozak** [comment]
fixed by https://github.com/MilosKozak/AndroidAPS/commit/66a19cce229ea06794e58ff29b85199579ef4671
