### ISSUE TITLE
[2.7.0-RC1] NPE in CareportalEvent

### ISSUE THREAD

**Issue by andyrozman** [MilosKozak/AndroidAPS#2840]
NullPointerException in CareportalEvent

2020-07-20 04:08:28.515 30568-11685/info.nightscout.androidaps E/DATASERVICE: [IntentService[DataService]]: [DataService.handleNewDataFromNSClient():178]: Unhandled exception
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String info.nightscout.androidaps.utils.DateUtil.dateAndTimeString(long)' on a null object reference
    	at info.nightscout.androidaps.db.CareportalEvent.toString(CareportalEvent.java:126) ~[na:0.0]
    	at info.nightscout.androidaps.services.DataService.storeMbg(DataService.java:251) ~[na:0.0]
    	at info.nightscout.androidaps.services.DataService.handleNewDataFromNSClient(DataService.java:174) ~[na:0.0]
    	at info.nightscout.androidaps.services.DataService.onHandleIntent(DataService.java:101) ~[na:0.0]
    	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:76) ~[na:0.0]
    	at android.os.Handler.dispatchMessage(Handler.java:106) ~[na:0.0]
    	at android.os.Looper.loop(Looper.java:193) ~[na:0.0]
    	at android.os.HandlerThread.run(HandlerThread.java:65) ~[na:0.0]

**Comment by MilosKozak** [comment]
fixed by https://github.com/MilosKozak/AndroidAPS/commit/74ca36bb6e5803d99f9b243bb4c099e507a29433
