### ISSUE TITLE
AAPS crashing (internal NS Client)

### ISSUE THREAD

**Issue by AdrianLxM** [MilosKozak/AndroidAPS#289]
This is the crash that @Heiner1 and @McHoffi are experiencing seen on Crashlytics:

```
Fatal Exception: java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 528852 bytes
       at android.app.ApplicationPackageManager.queryBroadcastReceiversAsUser(ApplicationPackageManager.java:889)
       at android.app.ApplicationPackageManager.queryBroadcastReceivers(ApplicationPackageManager.java:895)
       at info.nightscout.androidaps.plugins.NSClientInternal.broadcasts.BroadcastTreatment.handleNewTreatment(BroadcastTreatment.java:49)
       at info.nightscout.androidaps.plugins.NSClientInternal.services.NSClientService$8$1.run(NSClientService.java:507)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.os.HandlerThread.run(HandlerThread.java:61)
Caused by android.os.TransactionTooLargeException: data parcel size 528852 bytes
       at android.os.BinderProxy.transactNative(Binder.java)
       at android.os.BinderProxy.transact(Binder.java:615)
       at android.content.pm.IPackageManager$Stub$Proxy.queryIntentReceivers(IPackageManager.java:3417)
       at android.app.ApplicationPackageManager.queryBroadcastReceiversAsUser(ApplicationPackageManager.java:881)
       at android.app.ApplicationPackageManager.queryBroadcastReceivers(ApplicationPackageManager.java:895)
       at info.nightscout.androidaps.plugins.NSClientInternal.broadcasts.BroadcastTreatment.handleNewTreatment(BroadcastTreatment.java:49)
       at info.nightscout.androidaps.plugins.NSClientInternal.services.NSClientService$8$1.run(NSClientService.java:507)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.os.HandlerThread.run(HandlerThread.java:61)
```

I'm not familiar with the NSClient code so I leave this here.

**Comment by MilosKozak** [comment]
It's Android issue. System should accept data up to 1MB. This is crashing with 1/2

**Comment by AdrianLxM** [comment]
It seems not the actual broadcast that causes the problem.
What throws the runtime exception is the line
`List<ResolveInfo> x = context.getPackageManager().queryBroadcastReceivers(intent, 0);`
That is only needed for a debug output. (The amount of broadcast receivers for the broadcast already sent?)

@Heiner1, @McHoffi, could you please test if this branch resolves the problem: https://github.com/MilosKozak/AndroidAPS/tree/dev-nsclient-quickfix

**Comment by AdrianLxM** [comment]
The actual broadcast also seems to have problems:

```
07-16 17:13:37.009 31331-31331/com.eveningoutpost.dexdrip E/jamorham nsreceiver: Unknown action! info.nightscout.client.NEW_PROFILE
07-16 17:13:37.917 707-738/system_process E/JavaBinder: !!! FAILED BINDER TRANSACTION !!! (parcel size = 521544)
07-16 17:13:38.003 707-932/system_process E/JavaBinder: !!! FAILED BINDER TRANSACTION !!! (parcel size = 521544)
07-16 17:13:38.004 707-932/system_process E/ActivityManager: Exception thrown dispatching broadcasts in ProcessRecord{908b9cb 31714:com.eveningoutpost.dexdrip/u0a112}
java.lang.RuntimeException: data parcel size 521544 bytes
at com.android.server.am.BroadcastQueue.sendPendingBroadcastsLocked(BroadcastQueue.java:326)
at com.android.server.am.ActivityManagerService.sendPendingBroadcastsLocked(ActivityManagerService.java:17760)
at com.android.server.am.ActivityManagerService.attachApplicationLocked(ActivityManagerService.java:6847)
at com.android.server.am.ActivityManagerService.attachApplication(ActivityManagerService.java:6891)
at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:539)
at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2980)
at android.os.Binder.execTransact(Binder.java:565)
07-16 17:13:38.023 707-738/system_process E/JavaBinder: !!! FAILED BINDER TRANSACTION !!! (parcel size = 521600)
07-16 17:13:38.043 319-364/? E/BufferQueueProducer: [info.nightscout.androidaps/info.nightscout.androidaps.MainActivity] dequeueBuffer: BufferQueue has been abandoned
07-16 17:13:38.045 31567-31612/info.nightscout.androidaps E/OpenGLRenderer: GL error: Out of memory!
07-16 17:13:38.078 707-1401/system_process E/JavaBinder: !!! FAILED BINDER TRANSACTION !!! (parcel size = 521600)
07-16 17:13:38.080 707-1401/system_process E/ActivityManager: Exception thrown dispatching broadcasts in ProcessRecord{9d26861 31753:info.nightscout.androidaps/u0a145}
java.lang.RuntimeException: data parcel size 521600 bytes
at com.android.server.am.BroadcastQueue.sendPendingBroadcastsLocked(BroadcastQueue.java:326)
at com.android.server.am.ActivityManagerService.sendPendingBroadcastsLocked(ActivityManagerService.java:17760)
at com.android.server.am.ActivityManagerService.attachApplicationLocked(ActivityManagerService.java:6847)
at com.android.server.am.ActivityManagerService.attachApplication(ActivityManagerService.java:6891)
at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:539)
at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2980)
at android.os.Binder.execTransact(Binder.java:565)
```
It seems, this Exception is not catchable. Also it cannot be seen in Crashlytics

**Comment by AdrianLxM** [comment]
https://developer.android.com/reference/android/os/TransactionTooLargeException.html
> The Binder transaction buffer has a limited fixed size, currently 1Mb, which is shared by all transactions in progress for the process. Consequently this exception can be thrown when there are many transactions in progress even when most of the individual transactions are of moderate size.

**Comment by AdrianLxM** [comment]
Corresponding Fix/PR: https://github.com/MilosKozak/AndroidAPS/pull/299
