### ISSUE TITLE
Synchronize Interval access methods

### ISSUE THREAD

**Issue by AdrianLxM** [MilosKozak/AndroidAPS#298]
It is possible to reset/reload the data of Intervals (OverlappingIntervals, NonOverlappingIntervals, ProfileIntervals) (https://github.com/MilosKozak/AndroidAPS/blob/dev/app/src/main/java/info/nightscout/androidaps/data/OverlappingIntervals.java#L21) while a search process is still running on the data. Here e.g. `binarySearch` (https://github.com/MilosKozak/AndroidAPS/blob/dev/app/src/main/java/info/nightscout/androidaps/data/OverlappingIntervals.java#L69).

This could be the cause for:

```
java.lang.ArrayIndexOutOfBoundsException: length=14; index=74
                                                     at android.support.v4.util.LongSparseArray.valueAt(LongSparseArray.java:261)
                                                     at info.nightscout.androidaps.data.OverlappingIntervals.binarySearch(OverlappingIntervals.java:75)
                                                     at info.nightscout.androidaps.data.OverlappingIntervals.getValueByInterval(OverlappingIntervals.java:50)
                                                     at info.nightscout.androidaps.plugins.Treatments.TreatmentsPlugin.getRealTempBasalFromHistory(TreatmentsPlugin.java:258)
                                                     at info.nightscout.androidaps.plugins.Treatments.TreatmentsPlugin.getTempBasalFromHistor
```

**Comment by MilosKozak** [comment]
Check Iobcobcalculator plugin. The same issue is solved by locking access

**Comment by AdrianLxM** [comment]
I've added it to the PR https://github.com/MilosKozak/AndroidAPS/pull/286

As all access is done via non-static Object methods, declaring them `synchronized` should be the easiest way.

https://github.com/MilosKozak/AndroidAPS/pull/286/commits/76990b7983d02ecd352a4c8c953af742d7a942a7
