### ISSUE TITLE
Virtual Pump UI crashes

### ISSUE THREAD

**Issue by AdrianLxM** [MilosKozak/AndroidAPS#315]
```
07-23 01:48:06.086 20572-20572/info.nightscout.androidaps E/AndroidRuntime: FATAL EXCEPTION: main
                                                                            Process: info.nightscout.androidaps, PID: 20572
                                                                            java.lang.IllegalStateException: Recursive entry to executePendingTransactions
                                                                                at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1589)
                                                                                at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:570)
                                                                                at android.support.v4.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:164)
                                                                                at info.nightscout.androidaps.tabs.TabPageAdapter.finishUpdate(TabPageAdapter.java:40)
                                                                                at android.support.v4.view.ViewPager.populate(ViewPager.java:1177)
                                                                                at android.support.v4.view.ViewPager.populate(ViewPager.java:1025)
                                                                                at android.support.v4.view.ViewPager$3.run(ViewPager.java:254)
                                                                                at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
                                                                                at android.view.Choreographer.doCallbacks(Choreographer.java:686)
                                                                                at android.view.Choreographer.doFrame(Choreographer.java:618)
                                                                                at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
                                                                                at android.os.Handler.handleCallback(Handler.java:751)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                at android.os.Looper.loop(Looper.java:154)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:6186)
                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

This happens to me on 2 phones when I have the Virtual-Pump activated and open the tab for the first time. One cheap no name Android 5.1 phone and one MotoG-LTE with Lineage/Android  7.1.2

I guess it has to do with the handler started in `onCreate` modifying the GUI.

**Comment by MilosKozak** [comment]
https://github.com/MilosKozak/AndroidAPS/commit/d2a5939ce327633cd5cd958f1d379b54d1b2b930
