### ISSUE TITLE
Crash from stale data alarm logic

### ISSUE THREAD

**Issue by AdrianLxM** [MilosKozak/AndroidAPS#353]
```
08-12 10:51:47.859 30064-30064/info.nightscout.androidaps E/AndroidRuntime: FATAL EXCEPTION: main
                                                                            Process: info.nightscout.androidaps, PID: 30064
                                                                            java.lang.NullPointerException: Attempt to invoke virtual method 'boolean org.json.JSONObject.has(java.lang.String)' on a null object reference
                                                                                at info.nightscout.androidaps.plugins.NSClientInternal.data.NSSettingsStatus.getStringOrNull(NSSettingsStatus.java:204)
                                                                                at info.nightscout.androidaps.plugins.NSClientInternal.data.NSSettingsStatus.getExtendedSettings(NSSettingsStatus.java:157)
                                                                                at info.nightscout.androidaps.plugins.NSClientInternal.data.NSSettingsStatus.extentendedPumpSettings(NSSettingsStatus.java:311)
                                                                                at info.nightscout.androidaps.plugins.NSClientInternal.data.NSSettingsStatus.openAPSEnabledAlerts(NSSettingsStatus.java:348)
                                                                                at info.nightscout.androidaps.plugins.Overview.Notification.isAlarmForStaleData(Notification.java:169)
                                                                                at info.nightscout.androidaps.plugins.Overview.NotificationStore.unSnooze(NotificationStore.java:97)
                                                                                at info.nightscout.androidaps.plugins.Overview.OverviewFragment$29.run(OverviewFragment.java:1821)
                                                                                at android.app.Activity.runOnUiThread(Activity.java:5871)
                                                                                at info.nightscout.androidaps.plugins.Overview.OverviewFragment.updateNotifications(OverviewFragment.java:1816)
                                                                                at info.nightscout.androidaps.plugins.Overview.OverviewFragment.updateGUI(OverviewFragment.java:898)
                                                                                at info.nightscout.androidaps.plugins.Overview.OverviewFragment$1UpdateRunnable$1.run(OverviewFragment.java:863)
                                                                                at android.os.Handler.handleCallback(Handler.java:751)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                at android.os.Looper.loop(Looper.java:154)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:6186)
                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

**Comment by AdrianLxM** [comment]
@MilosKozak, @PoweRGbg, I have committed a quickfix to `dev` that allows AndroidAPS to start without crashes. Could you please check if that goes along with the stale data logic: https://github.com/MilosKozak/AndroidAPS/commit/f861546e12b50c6de93a88ce5634a472e479912f#diff-aa5d18a1463a67d677d6d190dd119bd7
