### ISSUE TITLE
Database exceptions in log

### ISSUE THREAD

**Issue by AdrianLxM** [MilosKozak/AndroidAPS#655]
Testing SMB with a DanaR:

```
08:07:27.981 [Thread-731] DEBUG [info.nightscout.androidaps.plugins.PumpDanaR.SerialIOThread:151]: >>>>> CMD_PUMP_EXPANS_INS_I 7e 7e 03 f1  02 07 c2 e7  2e 2e 
08:07:28.128 [Thread-733] DEBUG [info.nightscout.androidaps.plugins.PumpDanaR.SerialIOThread:75]: <<<<< CMD_PUMP_EXPANS_INS_I 7e 7e 0c f2  02 07 01 01  00 46 0f 00  00 00 00 ba  4a 2e 2e 
08:07:28.149 [Thread-733] ERROR [info.nightscout.androidaps.db.DatabaseHelper:1285]: Unhandled exception
java.sql.SQLException: Unable to run insert stmt on object E 0.00U/h @08:07 0/0min: INSERT INTO `ExtendedBoluses` (`_id` ,`date` ,`dia` ,`durationInMinutes` ,`insulin` ,`insulinInterfaceID` ,`isValid` ,`pumpId` ,`source` ) VALUES (?,?,?,?,?,?,?,?,?)
	at com.j256.ormlite.misc.SqlExceptionUtil.create(SqlExceptionUtil.java:22) ~[na:0.0]
	at com.j256.ormlite.stmt.mapped.MappedCreate.insert(MappedCreate.java:135) ~[na:0.0]
	at com.j256.ormlite.stmt.StatementExecutor.create(StatementExecutor.java:406) ~[na:0.0]
	at com.j256.ormlite.dao.BaseDaoImpl.create(BaseDaoImpl.java:308) ~[na:0.0]
	at info.nightscout.androidaps.db.DatabaseHelper.createOrUpdate(DatabaseHelper.java:1278) ~[na:0.0]
	at info.nightscout.androidaps.plugins.Treatments.TreatmentsPlugin.addToHistoryExtendedBolus(TreatmentsPlugin.java:405) ~[na:0.0]
	at info.nightscout.androidaps.plugins.ConfigBuilder.ConfigBuilderPlugin.addToHistoryExtendedBolus(ConfigBuilderPlugin.java:671) ~[na:0.0]
	at info.nightscout.androidaps.plugins.PumpDanaR.comm.MsgStatusBolusExtended.updateExtendedBolusInDB(MsgStatusBolusExtended.java:79) ~[na:0.0]
	at info.nightscout.androidaps.plugins.PumpDanaR.comm.MsgStatusBolusExtended.handleMessage(MsgStatusBolusExtended.java:49) ~[na:0.0]
	at info.nightscout.androidaps.plugins.PumpDanaR.SerialIOThread.run(SerialIOThread.java:79) ~[na:0.0]
Caused by: java.sql.SQLException: inserting to database failed: INSERT INTO `ExtendedBoluses` (`_id` ,`date` ,`dia` ,`durationInMinutes` ,`insulin` ,`insulinInterfaceID` ,`isValid` ,`pumpId` ,`source` ) VALUES (?,?,?,?,?,?,?,?,?)
	at com.j256.ormlite.misc.SqlExceptionUtil.create(SqlExceptionUtil.java:22) ~[na:0.0]
	at com.j256.ormlite.android.AndroidDatabaseConnection.insert(AndroidDatabaseConnection.java:159) ~[na:0.0]
	at com.j256.ormlite.stmt.mapped.MappedCreate.insert(MappedCreate.java:91) ~[na:0.0]
	... 8 common frames omitted
Caused by: android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: ExtendedBoluses.date (code 1555)
	at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method) ~[na:0.0]
	at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:798) ~[na:0.0]
	at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788) ~[na:0.0]
	at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86) ~[na:0.0]
	at com.j256.ormlite.android.AndroidDatabaseConnection.insert(AndroidDatabaseConnection.java:147) ~[na:0.0]
	... 9 common frames omitted
08:07:28.167 [Thread-733] ERROR [info.nightscout.androidaps.db.DatabaseHelper:1285]: Unhandled exception
java.sql.SQLException: Unable to run insert stmt on object E 1.40U/h @08:07 0/30min: INSERT INTO `ExtendedBoluses` (`_id` ,`date` ,`dia` ,`durationInMinutes` ,`insulin` ,`insulinInterfaceID` ,`isValid` ,`pumpId` ,`source` ) VALUES (?,?,?,?,?,?,?,?,?)
	at com.j256.ormlite.misc.SqlExceptionUtil.create(SqlExceptionUtil.java:22) ~[na:0.0]
	at com.j256.ormlite.stmt.mapped.MappedCreate.insert(MappedCreate.java:135) ~[na:0.0]
	at com.j256.ormlite.stmt.StatementExecutor.create(StatementExecutor.java:406) ~[na:0.0]
	at com.j256.ormlite.dao.BaseDaoImpl.create(BaseDaoImpl.java:308) ~[na:0.0]
	at info.nightscout.androidaps.db.DatabaseHelper.createOrUpdate(DatabaseHelper.java:1278) ~[na:0.0]
	at info.nightscout.androidaps.plugins.Treatments.TreatmentsPlugin.addToHistoryExtendedBolus(TreatmentsPlugin.java:405) ~[na:0.0]
	at info.nightscout.androidaps.plugins.ConfigBuilder.ConfigBuilderPlugin.addToHistoryExtendedBolus(ConfigBuilderPlugin.java:671) ~[na:0.0]
	at info.nightscout.androidaps.plugins.PumpDanaR.comm.MsgStatusBolusExtended.updateExtendedBolusInDB(MsgStatusBolusExtended.java:86) ~[na:0.0]
	at info.nightscout.androidaps.plugins.PumpDanaR.comm.MsgStatusBolusExtended.handleMessage(MsgStatusBolusExtended.java:49) ~[na:0.0]
	at info.nightscout.androidaps.plugins.PumpDanaR.SerialIOThread.run(SerialIOThread.java:79) ~[na:0.0]
Caused by: java.sql.SQLException: inserting to database failed: INSERT INTO `ExtendedBoluses` (`_id` ,`date` ,`dia` ,`durationInMinutes` ,`insulin` ,`insulinInterfaceID` ,`isValid` ,`pumpId` ,`source` ) VALUES (?,?,?,?,?,?,?,?,?)
	at com.j256.ormlite.misc.SqlExceptionUtil.create(SqlExceptionUtil.java:22) ~[na:0.0]
	at com.j256.ormlite.android.AndroidDatabaseConnection.insert(AndroidDatabaseConnection.java:159) ~[na:0.0]
	at com.j256.ormlite.stmt.mapped.MappedCreate.insert(MappedCreate.java:91) ~[na:0.0]
	... 8 common frames omitted
Caused by: android.database.sqlite.SQLiteConstraintException: UNIQUE constraint failed: ExtendedBoluses.date (code 1555)
	at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method) ~[na:0.0]
	at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:798) ~[na:0.0]
	at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788) ~[na:0.0]
	at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86) ~[na:0.0]
	at com.j256.ormlite.android.AndroidDatabaseConnection.insert(AndroidDatabaseConnection.java:147) ~[na:0.0]
	... 9 common frames omitted
08:07:28.172 [Thread-733] DEBUG [info.nightscout.androidaps.plugins.PumpDanaR.comm.MsgStatusBolusExtended:52]: Is extended bolus running: true
```
[AndroidAPS._2018-02-03_15-32-40_.0.zip](https://github.com/MilosKozak/AndroidAPS/files/1691912/AndroidAPS._2018-02-03_15-32-40_.0.zip)

**Comment by jotomo** [comment]
We should do more with those kind of errors than log them, since an administered bolus is not added to treatments and IOB. Logging to Fabric for debug and issuing a notification to the user seems appropriate.
