### ISSUE TITLE
Exception/Crash in Loop run

### ISSUE THREAD

**Issue by AdrianLxM** [MilosKozak/AndroidAPS#904]
```
04-21 03:27:38.056 12435-13842/? E/DetermineBasalAdapterSMBJS: [Thread-17] ERROR [info.nightscout.androidaps.plugins.OpenAPSSMB.DetermineBasalAdapterSMBJS:151]: RhinoException: (1052,0) org.mozilla.javascript.EcmaError: ReferenceError: "N" is not defined. (JavaScript#1052)
04-21 03:27:38.072 12435-13842/? E/AndroidRuntime: FATAL EXCEPTION: Thread-17
                                                   Process: info.nightscout.androidaps, PID: 12435
                                                   java.lang.RuntimeException: Could not dispatch event: class info.nightscout.androidaps.plugins.IobCobCalculator.events.EventAutosensCalculationFinished to handler [EventHandler public void info.nightscout.androidaps.plugins.Loop.LoopPlugin.onStatusEvent(info.nightscout.androidaps.plugins.IobCobCalculator.events.EventAutosensCalculationFinished)]: Attempt to read from field 'double info.nightscout.androidaps.plugins.Loop.APSResult.rate' on a null object reference
                                                       at com.squareup.otto.Bus.throwRuntimeException(Bus.java:460)
                                                       at com.squareup.otto.Bus.dispatch(Bus.java:387)
                                                       at com.squareup.otto.Bus.dispatchQueuedEvents(Bus.java:368)
                                                       at com.squareup.otto.Bus.post(Bus.java:337)
                                                       at info.nightscout.androidaps.plugins.IobCobCalculator.IobCobThread.run(IobCobThread.java:267)
                                                    Caused by: java.lang.NullPointerException: Attempt to read from field 'double info.nightscout.androidaps.plugins.Loop.APSResult.rate' on a null object reference
                                                       at info.nightscout.androidaps.plugins.OpenAPSSMB.OpenAPSSMBPlugin.invoke(OpenAPSSMBPlugin.java:217)
                                                       at info.nightscout.androidaps.plugins.Loop.LoopPlugin.invoke(LoopPlugin.java:261)
                                                       at info.nightscout.androidaps.plugins.Loop.LoopPlugin.onStatusEvent(LoopPlugin.java:139)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.squareup.otto.EventHandler.handleEvent(EventHandler.java:89)
                                                       at com.squareup.otto.Bus.dispatch(Bus.java:385)
                                                       at com.squareup.otto.Bus.dispatchQueuedEvents(Bus.java:368) 
                                                       at com.squareup.otto.Bus.post(Bus.java:337) 
                                                       at info.nightscout.androidaps.plugins.IobCobCalculator.IobCobThread.run(IobCobThread.java:267) 
```

**Comment by AdrianLxM** [comment]
My bad.
