### ISSUE TITLE
[RC1] Bolus progress dialog hangs

### ISSUE THREAD

**Issue by jotomo** [MilosKozak/AndroidAPS#939]
Somewhat recently the code was removed to keep the display on while a bolus was delivered.
When the display turns off while a bolus is in running and is turned on again after the bolus has finished, the dialog hangs. Could it be that when the bolus command submits _EventDismissBolusprogressIfRunning_ that the dialog isn't dismissed, because it's not _running_ (not displayed) and therefor the dismissal never happens?
Maybe in the _BolusProgressDialog_ set a flag _dismissPending_  (in the handler) if not currently displayed? We need to make sure we're not accidentally dismissing the dialog for a follow up bolus (if that's a possibility, possibly when issuing a bolus from the watch after a bolus from the phone).

**Comment by AdrianLxM** [comment]
The CommandQueue does not allow a new bolus if currently a bolus command is running.
The CommandQueue removes all bolus commands that are waiting in a queue when a new one gets entered.

If there are no race conditions with checking these conditions (running, remove prior) it should not be possible to have two boluses at once in the queue. (synchronization needed?)

**Comment by jotomo** [comment]
Thanks, forgot about that.
I'll need to dig deeper, can't easily reproduce the behaviour right now.

**Comment by jotomo** [comment]
```
java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
	at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:2055) ~[na:0.0]
	at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:2078) ~[na:0.0]
	at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:678) ~[na:0.0]
	at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:632) ~[na:0.0]
	at android.support.v4.app.DialogFragment.dismissInternal(DialogFragment.java:223) ~[na:0.0]
	at android.support.v4.app.DialogFragment.dismiss(DialogFragment.java:190) ~[na:0.0]
	at info.nightscout.androidaps.plugins.Overview.Dialogs.BolusProgressDialog.dismiss(BolusProgressDialog.java:86) ~[na:0.0]
	at info.nightscout.androidaps.plugins.Overview.Dialogs.BolusProgressDialog.lambda$null$2$BolusProgressDialog(BolusProgressDialog.java:151) ~[na:0.0]
	at info.nightscout.androidaps.plugins.Overview.Dialogs.BolusProgressDialog$$Lambda$3.run(Unknown Source) ~[na:0.0]
	at android.os.Handler.handleCallback(Handler.java:751) ~[na:0.0]
	at android.os.Handler.dispatchMessage(Handler.java:95) ~[na:0.0]
	at android.os.Looper.loop(Looper.java:154) ~[na:0.0]
	at android.app.ActivityThread.main(ActivityThread.java:6186) ~[na:0.0]
	at java.lang.reflect.Method.invoke(Native Method) ~[na:0.0]
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889) ~[na:0.0]
```
Theory: screen stays on until 100% is reached and `scheduleDismiss` is called. Screen turns off during the 5s wait window. When `dismiss` is called, the dialog is already closed. _onResume_ should dismiss the dialog due to _bolusEnded_ being set to true, however the method register on the event bus, and sets _running_ to _true_, before calling _dismiss_.
Testing the theory with the debugger, the app crashes with the above exception, possibly messing up state for _onResume_?

**Comment by jotomo** [comment]
https://fabric.io/nightscout3/android/apps/info.nightscout.androidaps/issues/5aea14e4638393737a05cb54?time=last-twenty-four-hours

**Comment by AdrianLxM** [comment]
I don't have that phenomenon on my phones, so I can't test it.
I'm putting this up for discussion: https://github.com/MilosKozak/AndroidAPS/pull/1000

**Comment by jotomo** [comment]
@soko78 We implemented a possible fix for this in RC3. Since the error isn't easily reproducible, it would be helpful if you could test RC3 and report back, whether it makes a difference or not. Thanks!

**Comment by soko78** [comment]
I have been using aaps-rc3 for one week now and this issue didn't appear again. Seems as if this is fixed.

**Comment by AdrianLxM** [comment]
Thanks for the feedback!
